# Generated by Django 4.1.2 on 2022-12-16 02:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user', 'bio']},
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blogger',
        ),
        migrations.AddField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Enter your blog text here.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(help_text='Enter your bio here.', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
